#!/bin/bash 
# https://github.com/caquino/redis-bash
# Poor man profiling - uncoment the next 2 lines
#set -x
#PS4='$(date "+%s.%N ($LINENO) + ")'
source redis-bash-lib
REDISPORT=6379
REPEAT=1
while getopts ":h:n:p:r:" opt
do
    case ${opt} in
        h) REDISHOST=${OPTARG};;
        n) REDISDB=${OPTARG};;
        p) REDISPORT=${OPTARG};;
        r) REPEAT=${OPTARG};;
    esac
done
shift $((${OPTIND} - 1))
if [ "${REDISHOST}" != "" ] && [ "${REDISPORT}" != "" ]
then
    exec 6<>/dev/tcp/${REDISHOST}/${REDISPORT} # open fd
else
    echo "Wrong arguments"
    exit 255
fi
[ "${REDISDB}" != "" ] && redis-client 6 SELECT ${REDISDB} > /dev/null
for ((z=1;z<=${REPEAT};z++))
do
    redis-client 6 "${@}"
    if [ $? -ne 0 ]; then
        exit 1
    fi
done
exec 6>&- #close fd
