#!/bin/bash 
# https://github.com/caquino/redis-bash
# run this file passing the channel to subscribe as argument
# ./redis-pubsub-test testchannel
# and on another shell publish a message on the same channel
# ./redis-bash-cli -h localhost PUBLISH testchannel Hello World
source redis-bash-lib
while true
do
    exec 5>&-
    exec 5<>/dev/tcp/localhost/6379
    redis-client 5 SUBSCRIBE ${1} > /dev/null # subscribe to the pubsub channel in fd 5
    while true
    do
        unset ARGV
        OFS=${IFS};IFS=$'\n' # split the return correctly
        ARGV=($(redis-client 5))
        IFS=${OFS}
        if [ "${ARGV[0]}" = "message" ] && [ "${ARGV[1]}" = "${1}" ]
        then
            echo "Message from pubsub channel: ${ARGV[2]}"
        elif [ -z ${ARGV} ]
        then
            sleep 1
            break
        fi
    done
done
